
---

# This playbook Installs the DVWA (Damn Vulnerable Web Application) container on the webserver group.
# It then creates an ELK (Elasticsearch, Logstash, & Kibana) container in the ELK group. After that, 
# it proceeds to install Filebeats & Metricbeats onto the webservers group so that the ELK group may
# more easily monitor what is going on. To expand either group, add the apprpriate IP addresses to the
# /etc/ansible/hosts file under the apprpriate headers. Make certain the apprpriate configuation files
# are located in the /etc/ansible/files directory and this playbook is located in the /etc/ansible/roles
# directory

# Set up target machines with the DVWA (Damn Vulnerable Web Application)
- name: Configure DVWA Web VM
  hosts: webservers
  become: true
  tasks:

    #Install docker
  - name: install docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present
    #Install pip3 to then use the Python Docker module
  - name: install pip3
    apt:
      name: python3-pip
      state: present
    #Install Docker module
  - name: install Python Docker Module
    pip:
      name: docker
      state: present
    #Launch the container for the webapp & open port 80
  - name: download and launch a docker web container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80
    #Enable docker to start on boot
  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes

# Set up ELK Machine to monitor the DVWA machines
- name: Configure ELK
  hosts: elk
  remote_user: azadmin
  become: true
  tasks:

    #Install docker
  - name: install docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present
    #Install pip3 to then use the Python Docker module
  - name: install pip3
    apt:
      name: python3-pip
      state: present
    #Install Docker module    
  - name: install Python Docker Module
    pip:
      name: docker
      state: present
    #Increase maximum virtual memory
  - name: Increase Virtual Memory
    command: sysctl -w vm.max_map_count=262144
    #Enable ELK to use increased virtual memory
  - name: use more Memory
    sysctl:
      name: vm.max_map_count
      value: "262144"
      state: present
      reload: yes
    #Download and launch ELK container
  - name: download and launch ELK container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
        - 5601:5601
        - 9200:9200 
        - 5044:5044
    #Enable container to start on boot
  - name: Enable service docker on boot
    systemd:
      name: docker
      enabled: yes

# Install Filebeat onto the DVWA machines to assist the ELK machine
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:

    #Download filebeat file
  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb
    #Install
  - name: install filebeat deb
    command: dpkg -i filebeat-7.4.0-amd64.deb
    #Move config file in appropriate directory
  - name: drop in filebeat.yml 
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml
    #Enable & configure the module
  - name: enable and configure system module
    command: filebeat modules enable system
    #Setup the module
  - name: setup filebeat
    command: filebeat setup -e
    #Start the module
  - name: start filebeat service
    command: service filebeat start
    #Enable container to start on boot
  - name: enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes

# Install Metricbeat onto the DVWA machines to assist the ELK machine
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:

    #Download Metricbeat file
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
    #Install
  - name: install metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb
    #move config file into appropriate directory
  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
    #Enable & configure the module
  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker
    #Setup the module
  - name: setup metric beat
    command: metricbeat setup
    #Start the module
  - name: start metric beat
    command: service metricbeat start
    #Enable container to start on boot
  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
